/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuotationRouteImport } from './routes/quotation'
import { Route as ProjectsNewRouteImport } from './routes/projects-new'
import { Route as ProjectsCrmNewRouteImport } from './routes/projects-crm-new'
import { Route as ProjectsCrmRouteImport } from './routes/projects-crm'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsNewRouteImport } from './routes/leads-new'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DashboardOldRouteImport } from './routes/dashboard-old'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfiguratorRouteImport } from './routes/configurator'
import { Route as IndexRouteImport } from './routes/index'

const QuotationRoute = QuotationRouteImport.update({
  id: '/quotation',
  path: '/quotation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects-new',
  path: '/projects-new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCrmNewRoute = ProjectsCrmNewRouteImport.update({
  id: '/projects-crm-new',
  path: '/projects-crm-new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCrmRoute = ProjectsCrmRouteImport.update({
  id: '/projects-crm',
  path: '/projects-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsNewRoute = LeadsNewRouteImport.update({
  id: '/leads-new',
  path: '/leads-new',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOldRoute = DashboardOldRouteImport.update({
  id: '/dashboard-old',
  path: '/dashboard-old',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguratorRoute = ConfiguratorRouteImport.update({
  id: '/configurator',
  path: '/configurator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configurator': typeof ConfiguratorRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-old': typeof DashboardOldRoute
  '/employees': typeof EmployeesRoute
  '/leads': typeof LeadsRoute
  '/leads-new': typeof LeadsNewRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/projects-crm': typeof ProjectsCrmRoute
  '/projects-crm-new': typeof ProjectsCrmNewRoute
  '/projects-new': typeof ProjectsNewRoute
  '/quotation': typeof QuotationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configurator': typeof ConfiguratorRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-old': typeof DashboardOldRoute
  '/employees': typeof EmployeesRoute
  '/leads': typeof LeadsRoute
  '/leads-new': typeof LeadsNewRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/projects-crm': typeof ProjectsCrmRoute
  '/projects-crm-new': typeof ProjectsCrmNewRoute
  '/projects-new': typeof ProjectsNewRoute
  '/quotation': typeof QuotationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configurator': typeof ConfiguratorRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-old': typeof DashboardOldRoute
  '/employees': typeof EmployeesRoute
  '/leads': typeof LeadsRoute
  '/leads-new': typeof LeadsNewRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/projects-crm': typeof ProjectsCrmRoute
  '/projects-crm-new': typeof ProjectsCrmNewRoute
  '/projects-new': typeof ProjectsNewRoute
  '/quotation': typeof QuotationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configurator'
    | '/contact'
    | '/dashboard'
    | '/dashboard-old'
    | '/employees'
    | '/leads'
    | '/leads-new'
    | '/login'
    | '/payments'
    | '/products'
    | '/projects'
    | '/projects-crm'
    | '/projects-crm-new'
    | '/projects-new'
    | '/quotation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configurator'
    | '/contact'
    | '/dashboard'
    | '/dashboard-old'
    | '/employees'
    | '/leads'
    | '/leads-new'
    | '/login'
    | '/payments'
    | '/products'
    | '/projects'
    | '/projects-crm'
    | '/projects-crm-new'
    | '/projects-new'
    | '/quotation'
  id:
    | '__root__'
    | '/'
    | '/configurator'
    | '/contact'
    | '/dashboard'
    | '/dashboard-old'
    | '/employees'
    | '/leads'
    | '/leads-new'
    | '/login'
    | '/payments'
    | '/products'
    | '/projects'
    | '/projects-crm'
    | '/projects-crm-new'
    | '/projects-new'
    | '/quotation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguratorRoute: typeof ConfiguratorRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DashboardOldRoute: typeof DashboardOldRoute
  EmployeesRoute: typeof EmployeesRoute
  LeadsRoute: typeof LeadsRoute
  LeadsNewRoute: typeof LeadsNewRoute
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  ProductsRoute: typeof ProductsRoute
  ProjectsRoute: typeof ProjectsRoute
  ProjectsCrmRoute: typeof ProjectsCrmRoute
  ProjectsCrmNewRoute: typeof ProjectsCrmNewRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  QuotationRoute: typeof QuotationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quotation': {
      id: '/quotation'
      path: '/quotation'
      fullPath: '/quotation'
      preLoaderRoute: typeof QuotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects-new': {
      id: '/projects-new'
      path: '/projects-new'
      fullPath: '/projects-new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects-crm-new': {
      id: '/projects-crm-new'
      path: '/projects-crm-new'
      fullPath: '/projects-crm-new'
      preLoaderRoute: typeof ProjectsCrmNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects-crm': {
      id: '/projects-crm'
      path: '/projects-crm'
      fullPath: '/projects-crm'
      preLoaderRoute: typeof ProjectsCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads-new': {
      id: '/leads-new'
      path: '/leads-new'
      fullPath: '/leads-new'
      preLoaderRoute: typeof LeadsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-old': {
      id: '/dashboard-old'
      path: '/dashboard-old'
      fullPath: '/dashboard-old'
      preLoaderRoute: typeof DashboardOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurator': {
      id: '/configurator'
      path: '/configurator'
      fullPath: '/configurator'
      preLoaderRoute: typeof ConfiguratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguratorRoute: ConfiguratorRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DashboardOldRoute: DashboardOldRoute,
  EmployeesRoute: EmployeesRoute,
  LeadsRoute: LeadsRoute,
  LeadsNewRoute: LeadsNewRoute,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  ProductsRoute: ProductsRoute,
  ProjectsRoute: ProjectsRoute,
  ProjectsCrmRoute: ProjectsCrmRoute,
  ProjectsCrmNewRoute: ProjectsCrmNewRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  QuotationRoute: QuotationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
